server:
  name: state-service
  port: 8080

redis:
  host: localhost:6379,localhost:6380,localhost:6381
  timeout: 30
  username: neo
  password: matrix
  useTLS: false

zookeeper:
  servers: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183

mongo:
  uri: mongodb://localhost:27017
  database: dhauli
  collection: context

kafka:
  brokers: 127.0.0.1:9093,127.0.0.1:9094,127.0.0.1:9095
  groupId: state-group
  topic: state
  routerTopic: router

discovery:
  id: state-service
  fqdn: state-service.localhost.k8s.local
  protocol: com.mangudaigb.dhauli.events.json.v1
  topic: state
  sessionTimeout: 10
  version: "0.0.1"

tracing:
  enabled: true
  Url: http://localhost:14268/api/traces

logger:
  env: dev
  level: INFO
  encoding: console
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
